sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: v5mh6OJQQowr5Jjl0ubP/JVsM7QuLQSA5SoR4w8puIEEd7Kbf2BAxTFDrQ4SLHDdiMtaCRnuSXO2zZe9WRKvzKr6T+tt3q0Dd8Tlknwhi9HsD3ljm5qJ0oonQMs9+o3gABqPI81ZrFvN1QZ/tzJR0DdddwplBb1uf6HCj2GWLOAOjFvk/Zp8M6Ovp4ke9AhgghYaSCzQjFhB+QDFEL4L4JrutC6K7QxJFmAgGkfflthBHnxPqawIxkuK2jqxdWTz4nf4d5yv5ErdSX6JtVjB0SDcin41a9D7jhjh6EThevWplyV2tnb3gqfAwoN1c9uPg07cLi174F57sUcRfyFS0TVDr4sYgdZ3gEWtcgF3Gs8s/XTfUes0jF5JnBPWB5CVoG3Mi98dgUF9seGBb14XerwqDWujZmgyWd6Ja9g21RMYd6x6xKv6Dl2RtDTwkHwoFgUkCtKkDk5cOpf9/RQM3ClMP+z4QcGLEvFNmjMQ9Dlc25SER9B35ByF7aZObFQOsoEWZiayfjpGQkvg5Kem1OMKJXo8akgoRB5TH7nJLyhCpM/VL9uVRixIhV/ofsAismUfsI4gZLzjQO4zghHYwEaptyacpidS+IbETAdxvUX3j2kFtY0lvThz5khX4r+XlCy6Bnj6wsm/zHeyhh3gwmm3XwHaUbA+Z7KyUiWkmj0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cowley-s-Essays_3549
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy